### PR TITLE
deps: upgrade dependencies

### PR DESCRIPTION
**Pull request by nicobav**
django-helusers to version 0.12.0 which contains python-jose related security fix.

Refs HAUKI-642

### CODE REVIEW

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr218.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __success__ for https://hauki-pr218.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr218.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __success__ for https://hauki-pr218.api.dev.hel.ninja :laughing::tada::tada::tada:

**Review by danipran — APPROVED** [review]
LGTM :+1:

**Pull request merged**
