### PR TITLE
Upgrade django to 4.2

### PR DESCRIPTION
**Pull request by nicobav**
also bump all "easy" applicable dependencies

Refs HAUKI-631

### CODE REVIEW

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr209.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __success__ for https://hauki-pr209.api.dev.hel.ninja :laughing::tada::tada::tada:

**Review by tuomas777 — APPROVED** [review]
The commit type should be `deps`, but other than that LGTM 🙂

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr209.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __success__ for https://hauki-pr209.api.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
