### PR TITLE
build: k6 load test OH-42

### PR DESCRIPTION
**Pull request by terovirtanen**
Load tests are run against stage environment
[OH-42](https://helsinkisolutionoffice.atlassian.net/browse/OH-42)

[OH-42]: https://helsinkisolutionoffice.atlassian.net/browse/OH-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
## api tests result is __success__ for https://hauki-pr199.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr199.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __success__ for https://hauki-pr199.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## api tests result is __success__ for https://hauki-pr199.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr199.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr199.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __success__ for https://hauki-pr199.api.dev.hel.ninja :laughing::tada::tada::tada:

**Review by danipran — APPROVED** [review]

**Pull request merged**
