### PR TITLE
Environment fixes

### PR DESCRIPTION
**Pull request by charn**
This PR introduces a few development environment related changes.

- A few docker warnings related to using obsolete keywords and non-matching word casing are fixed.
- `dev` service is renamed to `django` to be able to manage local containers with the same commands as with other projects.
- Note about `.git-blame-ignore-revs` is added to the README

### CODE REVIEW

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr223.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by danipran — APPROVED** [review]
Could also change `docker-compose.yml` to `compose.yaml`. Doesn't really affect anything, but it's [the preferred name for the Compose file](https://docs.docker.com/compose/compose-application-model/#the-compose-file).

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr223.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __success__ for https://hauki-pr223.api.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
