### PR TITLE
build: refactor pipelines OH-36

### PR DESCRIPTION
**Pull request by terovirtanen**
refactor pipelines,
[OH-36](https://helsinkisolutionoffice.atlassian.net/browse/OH-36)

[OH-36]: https://helsinkisolutionoffice.atlassian.net/browse/OH-36?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __failed__ for https://hauki-pr193.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __failed__ for https://hauki-pr193.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __success__ for https://hauki-pr193.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## api tests result is __failed__ for https://hauki-pr193.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __failed__ for https://hauki-pr193.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __failed__ for https://hauki-pr193.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __failed__ for https://hauki-pr193.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __failed__ for https://hauki-pr193.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## api tests result is __failed__ for https://hauki-pr193.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __failed__ for https://hauki-pr193.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## api tests result is __failed__ for https://hauki-pr193.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __failed__ for https://hauki-pr193.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __failed__ for https://hauki-pr193.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __failed__ for https://hauki-pr193.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __failed__ for https://hauki-pr193.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __failed__ for https://hauki-pr193.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __failed__ for https://hauki-pr193.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __success__ for https://hauki-pr193.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __success__ for https://hauki-pr193.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## api tests result is __success__ for https://hauki-pr193.api.dev.hel.ninja :laughing::tada::tada::tada:

**Review by danipran — APPROVED** [review]
LGTM! :+1:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr193.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __success__ for https://hauki-pr193.api.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
