### PR TITLE
HAUKI-669 | Switch to common reusable CI workflow

### PR DESCRIPTION
**Pull request by nicobav**
Refs HAUKI-669

### CODE REVIEW

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr254.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __success__ for https://hauki-pr254.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HAUKI-API branch is deployed to platta: https://hauki-pr254.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __success__ for https://hauki-pr254.api.dev.hel.ninja :laughing::tada::tada::tada:

**Review by tuomas777 — APPROVED** [review]
Great 👍 🦁

**Pull request merged**
